on:
  workflow_call:
    outputs:
      rockspecs: ${{ jobs.affected.outputs.rockspecs }}

jobs:

  affected:
    runs-on: ubuntu-20.04
    outputs:
      rockspecs: '["${{ steps.changed-files.outputs.all_modified_files }}"]'
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - id: changed-files
      uses: tj-actions/changed-files@v18
      with:
        files: |
          *.rockspec
          rockspecs/*.rockspec
        separator: '", "'
