name: Deploy

on: [ push, pull_request, workflow_dispatch ]

jobs:

  affected:
    uses: lunarmodules/.github/.github/workflows/list_affected_rockspecs.yml@sandbox

  build:
    needs: affected
    if: ${{ needs.affected.outputs.rockspecs }}
    uses: lunarmodules/.github/.github/workflows/test_build_rock.yml@sandbox
    with:
      rockspecs: ${{ needs.affected.outputs.rockspecs }}

  upload:
    needs: [ affected, build ]
    # Only run upload if:
    # 1. We are on the canonical repository (no uploads from forks)
    # 2. Some rockspecs were changed
    # Note there are additional guards against publishing in the reusable workflow
    if: >-
      ${{
        github.repository == 'lunarmodules/moon-sand' &&
        needs.affected.outputs.rockspecs
      }}
    uses: lunarmodules/.github/.github/workflows/upload_to_luarocks.yml@sandbox
    with:
      rockspecs: ${{ needs.affected.outputs.rockspecs }}
    secrets:
      apikey: ${{ secrets.LUAROCKS_APIKEY }}
