name: Deploy

on: [ push, workflow_dispatch ]

jobs:

  affected:
    uses: ./.github/workflows/list_affected_rockspecs.yml

  build:
    needs: affected
    if: ${{ needs.affected.outputs.rockspecs }}
    uses: ./.github/workflows/test_build_rock.yml
    with:
      rockspecs: ${{ needs.affected.outputs.rockspecs }}

  upload:
    needs: [ affected, build ]
    if: ${{ needs.affected.outputs.rockspecs }}
    uses: ./.github/workflows/upload_to_luarocks.yml
    with:
      rockspecs: ${{ needs.affected.outputs.rockspecs }}
    secrets:
      apikey: ${{ secrets.LUAROCKS_APIKEY }}
