name: Deploy

on: [ push, workflow_dispatch ]

jobs:

  affected:
    uses: ./.github/workflows/affected_rockspecs.yml

  build:
    if: ${{ needs.affected.outputs.rockspecs }}
    strategy:
      fail-fast: false
      matrix:
        rockspec: ${{ fromJSON(needs.affected.outputs.rockspecs) }}
    uses: ./.github/workflows/test_build_rock.yml
    with:
      rockspec: ${{ matrix.rockspec }}

  # upload:
  #   needs: [affected, build]
  #   # if: ${{ needs.affected.outputs.rockspecs && startsWith(github.ref, 'refs/tags/v') && github.repository == 'lunarmodules/moon-sand' }}
  #   if: ${{ needs.affected.outputs.rockspecs && github.ref_name == 'main' && github.repository == 'lunarmodules/moon-sand' }}
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       rockspec: ${{ fromJSON(needs.affected.outputs.rockspecs) }}
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Setup ‘lua’
  #       uses: leafo/gh-actions-lua@v9
  #     - name: Setup ‘luarocks’
  #       uses: leafo/gh-actions-luarocks@v4
  #     - name: Setup dependencies
  #       run: |
  #         luarocks install dkjson
  #     - run: |
  #         luarocks upload --force --api-key ${{ secrets.LUAROCKS_APIKEY }} -- ${{ matrix.rockspec }}
