name: Deploy

on: [ push, workflow_dispatch ]

jobs:

  affected:
    uses: alerque/lunarmodules-org-meta/.github/workflows/list_affected_rockspecs.yml@main

  debug:
    needs: affected
    runs-on: ubuntu-20.04
    if: ${{ needs.affected.outputs.rockspecs }}
    steps:
      - name: debug
        run: echo "GOT ${{ needs.affected.outputs.rockspecs }}"
      - name: flunk
        run: exit 1

  build:
    needs: [ affected, debug ]
    if: ${{ needs.affected.outputs.rockspecs }}
    uses: lunarmodules/.github/.github/workflows/test_build_rock.yml@main
    with:
      rockspecs: ${{ needs.affected.outputs.rockspecs }}

  upload:
    needs: [ affected, build ]
    # Only run upload if:
    # 1. Some rockspecs were changed — this implies the commit changing the rockspec is the same one that gets tagged
    # 2. The current commit is either tagged or on the default branch (the workflow will upload dev/scm rockspecs any
    #    time they are touched, tagged ones whenever the edited rockspec and tag match)
    # 3. We are on the canonical repository (no uploads from forks)
    if: >-
      ${{
        needs.affected.outputs.rockspecs &&
        ( github.ref_name == 'master' || startsWith(github.ref, 'refs/tags/') ) &&
        github.repository == 'lunarmodules/moon-sand'
      }}
    uses: lunarmodules/.github/.github/workflows/upload_to_luarocks.yml@main
    with:
      rockspecs: ${{ needs.affected.outputs.rockspecs }}
    secrets:
      apikey: ${{ secrets.LUAROCKS_APIKEY }}
