name: Demo Action Issue 12

on: [push, pull_request]

jobs:

  busted:
    strategy:
      fail-fast: false
      matrix:
        luaVersion:
          - [ '5.4', 'MYCFLAGS=-fPIC' ]
          - [ '5.3', 'MYCFLAGS=-fPIC' ]
          - [ '5.2', 'MYCFLAGS=-fPIC' ]
          - [ '5.1', 'CFLAGS="-O2 -Wall -DLUA_USE_LINUX -fPIC"']
          - [ 'luajit', 'XCFLAGS=-fPIC' ]
          - [ 'luajit-openresty', 'XCFLAGS=-fPIC' ]
        luarocksVersion: [ "3.8.0" ]
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup ‘lua’
      uses: leafo/gh-actions-lua@v9
      with:
        luaVersion: ${{ matrix.luaVersion[0] }}
        luaCompileFlags: ${{ matrix.luaVersion[1] }}
    - name: Setup ‘luarocks’
      uses: leafo/gh-actions-luarocks@v4
      with:
        luarocksVersion: ${{ matrix.luarocksVersion }}
    - name: List installed rocks after default action init
      run: luarocks list
    - name: Test if Luarocks can download something
      run: luarocks install busted
