name: Demo Action Issue 8

on: [push, pull_request]

jobs:

  busted:
    strategy:
      fail-fast: false
      matrix:
        luaVersion: [ "5.4", "5.3", "5.2", "5.1" ]
        luarocksVersion: [ "3.8.0", "3.1.3", "2.4.2" ]
        exclude:
          - luaVersion: "5.4"
            luarocksVersion: "2.4.2"
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup ‘lua’
      uses: leafo/gh-actions-lua@v9
      with:
        luaVersion: ${{ matrix.luaVersion }}
    - name: Setup ‘luarocks’
      uses: leafo/gh-actions-luarocks@v4
      with:
        luarocksVersion: ${{ matrix.luarocksVersion }}
    - name: Test luarocks download functionality
      run: luarocks install luacheck
