name: Demo Action Issue 12

on: [push, pull_request]

jobs:

  busted:
    strategy:
      fail-fast: false
      matrix:
        luaVersion: [ "5.4" ]
        luarocksVersion: [ "3.8.0" ]
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup ‘lua’
      uses: leafo/gh-actions-lua@v9
      with:
        luaVersion: ${{ matrix.luaVersion }}
    - name: Setup ‘luarocks’
      uses: leafo/gh-actions-luarocks@v4
      with:
        luarocksVersion: ${{ matrix.luarocksVersion }}
    - name: Test if Luarocks can download something
      run: luarocks install busted
