name: Upload to LuaRocks

on:
  workflow_call:
    inputs:
      rockspecs:
        required: true
        type: string
    secrets:
      apikey:
        required: true

jobs:
  upload:
    name: Build rocks and upload to LuaRocks
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        rockspec: ${{ fromJSON(inputs.rockspecs) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup ‘lua’
        uses: leafo/gh-actions-lua@v9
      - name: Setup ‘luarocks’
        uses: leafo/gh-actions-luarocks@v4
      - name: Setup dependencies
        run: |
          luarocks install dkjson
      - name: Upload rockspec to luarocks.org
        run: |
          luarocks upload ${{ contains(matrix.rockspec, '-dev-') && '--force --skip-pack' }} --api-key ${{ secrets.apikey }} -- ${{ matrix.rockspec }}

  #   # if: ${{ startsWith(github.ref, 'refs/tags/v')
